apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-init-sql
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  init-replication-user.sql: |
    CREATE USER IF NOT EXISTS 'replica'@'%' IDENTIFIED WITH mysql_native_password BY '${REPL_PASSWORD}';
    GRANT REPLICATION SLAVE ON *.* TO 'replica'@'%';
    FLUSH PRIVILEGES;
