{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.secretName" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.rootPasswordKey }}: {{ .Values.auth.rootPassword | quote }}
  {{ .Values.auth.replicationPasswordKey }}: {{ .Values.auth.replicationPassword | quote }}
{{- end }}
