apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-write
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "mysql.fullname" . }}-0
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-read
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mysql.selectorLabels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
